image:
  file: .gitpod.Dockerfile

tasks:
  - before: |
      printf 'export PATH="%s:$PATH"\n' "~/.local/bin" >> $HOME/.bashrc && exit
  - init: |
      pip3 install pylint pycodestyle
  - command: |
      source ~/.bashrc
      clear
vscode:
  extensions:
    - ms-python.python